require 'zabbixapi/base'

require 'zabbixapi/user'
require 'zabbixapi/host'
require 'zabbixapi/item'
require 'zabbixapi/graph'
require 'zabbixapi/group'
require 'zabbixapi/screen'
require 'zabbixapi/trigger'
require 'zabbixapi/template'
require 'zabbixapi/usermacro'
require 'zabbixapi/application'
